// Auto-generated by @decocms/start/scripts/generate-sections.ts
// Do not edit manually. Add convention exports to your section files instead.
//
// Supported conventions:
//   export const eager = true       → prefer eager (defers past fold threshold)
//   export const neverDefer = true  → ALWAYS eager, ignores fold threshold
//   export const cache = "listing"  → SWR-cached section loader results
//   export const layout = true      → cached as layout (Header, Footer, Theme)
//   export const sync = true        → bundled synchronously (not lazy-loaded)
//   export const clientOnly = true  → skip SSR (client-only rendering)
//   export const seo = true         → SEO section (provides page head data)
//   export function LoadingFallback → skeleton shown while section loads

import * as _sync0 from "../../sections/Hero";

export interface SectionMetaEntry {
  eager?: boolean;
  cache?: string;
  layout?: boolean;
  sync?: boolean;
  clientOnly?: boolean;
  seo?: boolean;
  hasLoadingFallback?: boolean;
}

export const sectionMeta: Record<string, SectionMetaEntry> = {
  "site/sections/Hero.tsx": { eager: true, sync: true },
};

export const syncComponents: Record<string, any> = {
  "site/sections/Hero.tsx": _sync0,
};

export const loadingFallbacks: Record<string, React.ComponentType<any>> = {};
