/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as DecoMetaRouteImport } from './routes/deco/meta'
import { Route as DecoRenderRouteImport } from './routes/deco/render'
import { Route as DecoInvokeSplatRouteImport } from './routes/deco/invoke.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DecoMetaRoute = DecoMetaRouteImport.update({
  id: '/deco/meta',
  path: '/deco/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const DecoRenderRoute = DecoRenderRouteImport.update({
  id: '/deco/render',
  path: '/deco/render',
  getParentRoute: () => rootRouteImport,
} as any)
const DecoInvokeSplatRoute = DecoInvokeSplatRouteImport.update({
  id: '/deco/invoke/$',
  path: '/deco/invoke/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/deco/meta': typeof DecoMetaRoute
  '/deco/render': typeof DecoRenderRoute
  '/deco/invoke/$': typeof DecoInvokeSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/deco/meta': typeof DecoMetaRoute
  '/deco/render': typeof DecoRenderRoute
  '/deco/invoke/$': typeof DecoInvokeSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/deco/meta': typeof DecoMetaRoute
  '/deco/render': typeof DecoRenderRoute
  '/deco/invoke/$': typeof DecoInvokeSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/deco/meta' | '/deco/render' | '/deco/invoke/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/deco/meta' | '/deco/render' | '/deco/invoke/$'
  id: '__root__' | '/' | '/$' | '/deco/meta' | '/deco/render' | '/deco/invoke/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  DecoMetaRoute: typeof DecoMetaRoute
  DecoRenderRoute: typeof DecoRenderRoute
  DecoInvokeSplatRoute: typeof DecoInvokeSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deco/meta': {
      id: '/deco/meta'
      path: '/deco/meta'
      fullPath: '/deco/meta'
      preLoaderRoute: typeof DecoMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deco/render': {
      id: '/deco/render'
      path: '/deco/render'
      fullPath: '/deco/render'
      preLoaderRoute: typeof DecoRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deco/invoke/$': {
      id: '/deco/invoke/$'
      path: '/deco/invoke/$'
      fullPath: '/deco/invoke/$'
      preLoaderRoute: typeof DecoInvokeSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  DecoMetaRoute: DecoMetaRoute,
  DecoRenderRoute: DecoRenderRoute,
  DecoInvokeSplatRoute: DecoInvokeSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
